### ISSUE TITLE
I tried to get this to work on my machine and noticed that you are a poo

### ISSUE THREAD

**Issue by amxelemara** [Taha-Hassan-Git/colorpicker#1]
Like title says, I couldn't help but notice that you are a poo.
Happy to help fix this but maybe need some suggestions?

**Comment by Taha-Hassan-Git** [comment]
Hey, I've checked this from my end and I haven't been able to replicate the issue. I think maybe you were looking in the mirror.

**Comment by amxelemara** [comment]
No, I'm quite sure this is a real issue. 
I've taken a screenshot of what I'm looking at [here](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Emoji_u1f4a9.svg/1200px-Emoji_u1f4a9.svg.png).

Please advise!
